In [4]:
import numpy as np

In [5]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [6]:
b = np.array([[1,2,3],[4,5,6],[1,2,3] ])
print(b)

[[1 2 3]
 [4 5 6]
 [1 2 3]]


In [7]:
print(a.ndim,b.ndim)

1 2


In [8]:
a.shape

(3,)

In [9]:
b.shape

(3, 3)

In [10]:
print(a.dtype)
print(b.dtype)
a.dtype

int64
int64


dtype('int64')

In [11]:
print(a.itemsize)
print(b.itemsize)

8
8


In [12]:
print(a.nbytes)  

24


In [17]:
print(a[2])
print(b[1,1])

3
5


In [30]:
#SLICING
print(a[0:])
print(b[0:2])
print(b[0:2,::2])

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[1 3]
 [4 6]]


In [37]:
#MODIFYING
b[1,2] = 10
print(b)
b[:,2] = [1,2,3]
print(b)

[[ 1  2  3]
 [ 4  5 10]
 [ 1  2  3]]
[[1 2 1]
 [4 5 2]
 [1 2 3]]


#####3D

In [42]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)
print(c[0,1,:])
print(c[:,1,:])
c[:,:,1] = [2,2]
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[3 4]
[[3 4]
 [7 8]]
[[[1 2]
  [3 2]]

 [[5 2]
  [7 2]]]


######INITALIZING DIFFERENT TYPES OF ARRAYS

In [50]:
a = np.zeros((2,3))
print(a)
b = np.ones((4,2,2))
print(b)
np.full((2,2),99)

[[0. 0. 0.]
 [0. 0. 0.]]
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


array([[99, 99],
       [99, 99]])

In [53]:
np.full_like(a,4)

array([[4., 4., 4.],
       [4., 4., 4.]])

In [60]:
# Random Decimal Numbers
print(np.random.random_sample((2,2)))
print(np.random.rand(3,2))

[[0.86294467 0.74291109]
 [0.91081034 0.37843955]]
[[0.675788   0.06762031]
 [0.49136599 0.98152364]
 [0.73861891 0.36980892]]


In [63]:
print(np.random.randint(1,10,(3,3)))
print(np.random.randint(-4,10,size = (3,3)))

[[3 1 8]
 [8 6 9]
 [4 1 3]]
[[-4  6  5]
 [ 1 -1 -3]
 [ 3 -1  0]]


In [64]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [73]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [80]:
output = np.ones((5,5))
z = np.zeros((3,3))
z[1,1] = 9
output[1:4,1:4]=z
print(z)
print(output)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [81]:
###### Copying Of array

In [83]:
a = [1,2,3]
b = a
b[1] = 5
print(a)
print(b)
c = a.copy()
c[1] = 10
print(c)

[1, 5, 3]
[1, 5, 3]
[1, 10, 3]


In [96]:
e = np.array([1,2,3])
print(e+2)
print(e-2)
print(e*2)
print(e/2)
print(e**2)
print(np.sin(e))
print(np.cos(e))

[3 4 5]
[-1  0  1]
[2 4 6]
[0.5 1.  1.5]
[1 4 9]
[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]


In [97]:
# Linear Algebra

In [108]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),4)
print(b)

np.dot(a,b)

np.linalg.det(np.full((3,3),1))
c = np.identity(3)
print(c)
np.linalg.det(c)

[[1. 1. 1.]
 [1. 1. 1.]]
[[4 4]
 [4 4]
 [4 4]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

In [109]:
# Statistics

In [117]:
c = np.array([[1,2,3],[4,5,6]])
print(c)
np.min(c)
np.max(c)
print(np.min(c,axis=1))
print(np.min(c,axis=0))
print(np.sum(c,axis=1))

[[1 2 3]
 [4 5 6]]
[1 4]
[1 2 3]
[ 6 15]


In [118]:
# Reorganizing Arrays

In [122]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

after = arr.reshape(2,2,2)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [126]:
# Vertically Stacking Vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
print(np.vstack([v1,v2,v1,v2]))

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


In [128]:
# Horizontally Stacking Vectors
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
print(h1)
print(h2)
np.hstack([h1,h2])

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])